version: "3.8"

services:
  postgres:
    image: postgres:12.4
    hostname: localhost
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
    environment:
      TZ: UTC
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retro_board
